package webMagic;

import com.alibaba.fastjson.JSON;
import com.alibaba.fastjson.JSONObject;

import java.util.ArrayList;
import java.util.List;

public class CdpCollectDef {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.id
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private Integer id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.collect_name
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private String collectName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.data_domain
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private String dataDomain;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.user_id
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private Long userId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.next_page
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private String nextPage;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.next_page_type
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private Integer nextPageType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.collect_url
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private String collectUrl;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.next_page_total
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private Integer nextPageTotal;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column cdp_collect_def.collect_param
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    private List<ParamRule> collectParam;

    private String headers;
    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.id
     *
     * @return the value of cdp_collect_def.id
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.id
     *
     * @param id the value for cdp_collect_def.id
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.collect_name
     *
     * @return the value of cdp_collect_def.collect_name
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public String getCollectName() {
        return collectName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.collect_name
     *
     * @param collectName the value for cdp_collect_def.collect_name
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setCollectName(String collectName) {
        this.collectName = collectName == null ? null : collectName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.data_domain
     *
     * @return the value of cdp_collect_def.data_domain
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public String getDataDomain() {
        return dataDomain;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.data_domain
     *
     * @param dataDomain the value for cdp_collect_def.data_domain
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setDataDomain(String dataDomain) {
        this.dataDomain = dataDomain == null ? null : dataDomain.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.user_id
     *
     * @return the value of cdp_collect_def.user_id
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.user_id
     *
     * @param userId the value for cdp_collect_def.user_id
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.next_page
     *
     * @return the value of cdp_collect_def.next_page
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public String getNextPage() {
        return nextPage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.next_page
     *
     * @param nextPage the value for cdp_collect_def.next_page
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setNextPage(String nextPage) {
        this.nextPage = nextPage == null ? null : nextPage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.next_page_type
     *
     * @return the value of cdp_collect_def.next_page_type
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public Integer getNextPageType() {
        return nextPageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.next_page_type
     *
     * @param nextPageType the value for cdp_collect_def.next_page_type
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setNextPageType(Integer nextPageType) {
        this.nextPageType = nextPageType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.collect_url
     *
     * @return the value of cdp_collect_def.collect_url
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public String getCollectUrl() {
        return collectUrl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.collect_url
     *
     * @param collectUrl the value for cdp_collect_def.collect_url
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setCollectUrl(String collectUrl) {
        this.collectUrl = collectUrl == null ? null : collectUrl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.next_page_total
     *
     * @return the value of cdp_collect_def.next_page_total
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public Integer getNextPageTotal() {
        return nextPageTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.next_page_total
     *
     * @param nextPageTotal the value for cdp_collect_def.next_page_total
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setNextPageTotal(Integer nextPageTotal) {
        this.nextPageTotal = nextPageTotal;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column cdp_collect_def.collect_param
     *
     * @return the value of cdp_collect_def.collect_param
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public String getCollectParam() {
        return JSON.toJSONString(collectParam);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column cdp_collect_def.collect_param
     *
     * @param collectParam the value for cdp_collect_def.collect_param
     *
     * @mbg.generated Mon May 04 12:44:32 CST 2020
     */
    public void setCollectParam(String collectParam) {
        this.collectParam=null;//重置m
        if(collectParam!=null&&!collectParam.equals("")){
            this.collectParam = JSONObject.parseArray(collectParam, ParamRule.class);
        }
    }

    public List<ParamRule> getCollectParamList(){
        return collectParam;
    }

    public void setCollectParam(List<ParamRule> collectParam) {
        this.collectParam = collectParam;
    }

    @Override
    public String toString() {
        return "CdpCollectDef{" +
                "id=" + id +
                ", collectName='" + collectName + '\'' +
                ", dataDomain='" + dataDomain + '\'' +
                ", userId=" + userId +
                ", nextPage='" + nextPage + '\'' +
                ", nextPageType=" + nextPageType +
                ", collectUrl='" + collectUrl + '\'' +
                ", nextPageTotal=" + nextPageTotal +
                ", collectParam=" + collectParam +
                ", headers='" + headers + '\'' +
                '}';
    }
}